# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1024)),
                ('port', models.IntegerField()),
                ('type', models.CharField(choices=[('L', 'linux'), ('W', 'windows')], max_length=30)),
            ],
        ),
    ]
