# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('item', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Prohost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_path', models.CharField(max_length=1024)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=50)),
                ('svn_path', models.CharField(max_length=1024)),
                ('src_path', models.CharField(max_length=1024)),
                ('propath', models.TextField(max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='prohost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.Project'),
        ),
        migrations.AddField(
            model_name='entry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.Project'),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
