# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_rollback'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollback',
            name='rolldate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
